title: Jekyll Bookshop Starter
email: support@cloudcannon.com

source: site

plugins:
  - jekyll-bookshop

# Multiple bookshops can be used on one website,
# or different production / staging locations.
bookshop_locations:
  - ../component-library

exclude:
  - node_modules

include:
  - _cloudcannon # This exposes the live editing data to CloudCannon

# The rest of this array structure will be
# populated by the bookshop-array-structures plugin.
_array_structures:
  content_blocks:
    style: modal

defaults:
  - scope:
      path: ""
    values:
      layout: default
